name: Release Merge

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, closed]

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-and-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release')
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check version consistency
      id: version_check
      run: |
        PULL_REQUEST_NAME=${{ github.event.pull_request.title }}
        echo "Pull request title: $PULL_REQUEST_NAME"
        # Extract the version from foo/__init__.py
        VERSION=$(grep __version__ foo/__init__.py | cut -d'"' -f2)

        # Extract the version from the Pull request name
        BRANCH_VERSION=$(echo $PULL_REQUEST_NAME | cut -d'/' -f2)

        # Compare the versions
        if [ "$VERSION" != "$BRANCH_VERSION" ]; then
          echo "::error::version mismatch between foo/__init__.py=$VERSION and branch=$BRANCH_VERSION"
          exit 1
        fi
        # Set output new version
        echo "tag=${BRANCH_VERSION}" >> $GITHUB_OUTPUT

    # https://github.com/rickstaa/action-create-tag
    - name: Tag
      if: github.event.pull_request.merged == true && github.event.pull_request.merged_by != null
      uses: rickstaa/action-create-tag@v1
      id: tag_create
      with:
        tag: ${{ steps.version_check.outputs.tag }}
        message: Release ${{ steps.version_check.outputs.tag }}